fs = require 'fs'
path = require 'path'
stitch = require 'stitch'
{Parser} = require 'jison'

ENC = 'utf8'
GRAMMAR = './grammar.jison'
TMP_STITCH_DIR = path.resolve __dirname, './tmp'
TMP_TARGET_FN = path.resolve TMP_STITCH_DIR, 'genome-parser.js'

task 'cafebuild', 'build with cafe', cafebuild = (cb) ->
    unless process.env.CAFE_TMP_BUILD_ROOT and process.env.CAFE_TARGET_FN
        throw "No CAFE_TMP_BUILD_ROOT and/or CAFE_TARGET_FN found in env"

    tmp_build_root = process.env.CAFE_TMP_BUILD_ROOT

    target_fn = (path.resolve process.env.CAFE_TMP_BUILD_ROOT, 
                              process.env.CAFE_TARGET_FN)

    fs.readFile GRAMMAR, ENC, (err, grammar) ->
        throw err if err

        dna_parser = new Parser grammar
        dna_parser_source = dna_parser.generate()

        fs.writeFile TMP_TARGET_FN, dna_parser_source, ENC, (err) ->
            throw err if err

            pkg = stitch.createPackage paths: [TMP_STITCH_DIR]
            pkg.compile (err, stitched_src) ->
                throw err if err

                fs.writeFile target_fn, stitched_src, ENC, cb
    


